from classifier_app.components.data_ingestion import DataIngestion
from classifier_app.components.prepare_base_model import PrepareBaseModel
from classifier_app.components.training import  Training
from classifier_app.components.prepare_callbacks import PrepareCallback
from classifier_app.components.evaluate_model import Evaluate_Model