TRAIN_RATIO: 0.7
TEST_RATIO: 0.3



AUGMENTATION: True
IMAGE_SIZE: [224,224,3]

INCLUDE_TOP: False

CLASSES: 2
WEIGHTS: imagenet
LEARNING_RATE: 0.01

BATCH_SIZE: 8
EPOCHS: 1
INTERPOLATION : "bilinear"